# Generated by Django 5.0.7 on 2024-07-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafget_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('car', 'car'), ('bike', 'bike'), ('walk', 'walk')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=100)),
                ('resto_name_en', models.CharField(max_length=100, null=True)),
                ('resto_name_ru', models.CharField(max_length=100, null=True)),
                ('resto_name_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ManyToManyField(to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.courier')),
                ('resto_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.food')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('доставлено', 'доставлено'), ('В обработке', 'В обработке'), ('В пути', 'В пути')], max_length=100)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('parent_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.review')),
                ('resto_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], default='bronze', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating')),
                ('resto_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.food')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.userprofile'),
        ),
    ]
